/* confdefs.h */
#define PACKAGE_NAME "aria2"
#define PACKAGE_TARNAME "aria2"
#define PACKAGE_VERSION "1.37.0"
#define PACKAGE_STRING "aria2 1.37.0"
#define PACKAGE_BUGREPORT "https://github.com/aria2/aria2/issues"
#define PACKAGE_URL "https://aria2.github.io/"
#define PACKAGE "aria2"
#define VERSION "1.37.0"
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_WCHAR_H 1
